<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: trapta
 * Date: Fri, 17 Aug 2018 08:04:23 +0200
 */

$conf['title'] = 'TRAPTA';
$conf['start'] = 'trapta';
$conf['template'] = 'LeonStaufer-material';
$conf['license'] = '0';
$conf['recent'] = 0;
$conf['recent_days'] = 0;
$conf['breadcrumbs'] = 0;
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'index,recent,revisions,register,profile,profile_delete,check,rss,subscribe,unsubscribe,source,export_raw';
$conf['securecookie'] = 0;
$conf['htmlok'] = 1;

// end auto-generated content
